POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  
  "fullName": "Kenedy Maina",
  "email": "kennynet66@gmail.com",
  "phoneNumber": "0708530896",
  "password": "test12"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "string",
  "password": "string"
}

###
