POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  
  "fullName": "Yoshi",
  "email": "yoshi@google.com",
  "phoneNumber": "0712345678",
  "password": "test12"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "yoshi@google.com",
  "password": "test12"
}

###
