POST http://localhost:3000/api/tours/createTour
Content-Type: application/json

{
  "Destination": "Mount Kenya ",
  "Tour_type": "Hiking",
  "Duration": "3 Days",
  "Price": "Kshs 15,000",
  "Image": "https://i.pinimg.com/564x/ef/ed/4b/efed4b90925ce731a690449c89f221aa.jpg"
}

###

GET http://localhost:3000/api/tours/tourId/60d96911-e7c8-4ebd-9679-bdc39935651d
Content-Type: application/json

###
GET http://localhost:3000/api/tours/allTours
Content-Type: application/json

###
DELETE  http://localhost:3000/api/tours/deleteTour/60d96911-e7c8-4ebd-9679-bdc39935651d
Content-Type: application/json

###

PUT http://localhost:3000/api/tours/updateTour/d8ea3307-8971-499b-b0ca-e5b7442996e4
Content-Type: application/json

{
  "Destination": "Mount Kenya ",
  "Tour_type": "Weekend Gateway",
  "Duration": "3 Days",
  "Price": "Kshs 15,000",
  "Image": "https://i.pinimg.com/564x/ef/ed/4b/efed4b90925ce731a690449c89f221aa.jpg"

}