
###
//GET ALL USERS
GET http://localhost:3000/api/users/allUsers
Content-Type: application/json


###
//GET USER  PROFILE
GET http://localhost:3000/api/users/getProfile/0a2a39a1-6aa0-408c-8b77-a559e17dc94e
Content-Type: application/json


###
//DELETE USER PROFILE
DELETE   http://localhost:3000/api/users/deleteUser/e6618f09-be7e-41d3-a3d5-da96fcb0f484